package main;

import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.UnsupportedLookAndFeelException;

import configuracion.Parametros;

/**
 * Clase principal del juego. Se trata de un <code>JFrame</code> sobre el que se declarará, 
 * en un principio, un <code>PanelPresentacion</code> que servirá de introducción al juego. 
 * Una vez se cumplan las condiciones marcadas en dicho <code>PanelPresentacion</code>, éste
 * será eliminado y sobre el frame principal se situará un nuevo <code>PanelJuego</code>, ya con 
 * el contenido jugable.
 * 
 * @author ActionPerformed
 * @version 1.0, 6 Jun 2014
 * @see PanelPresentacion
 * @see PanelJuego
 */
public final class Main extends JFrame {

	private static final long serialVersionUID = 8121299466984376793L;
	private PanelPresentacion panelPresentacion;
    private PanelJuego panelJuego;
    
    /**
     * Crea un nuevo elemento <code>Main</code>
     */
    public Main(){
        initComponents();
        initMoreComponents();
    }
    
    /**
     * Continua con la inicialización de parámetros del <code>Main</code>, centrándolo
     * en pantalla, fijando el idioma como español y situando sobre él un <code>PanelPresentacion</code>
     * 
     * @see PanelPresentacion
     */
    public void initMoreComponents(){
        
        setLocationRelativeTo(null); //centro el frame en la pantalla
        configuracion.Parametros.getInstance().setLocalizacion(new Locale("es")); //Fijo idioma
        this.setVisible(true);
        panelPresentacion = new PanelPresentacion(this);
        panelPresentacion.setBounds(
                0,
                0,
                Parametros.getInstance().getANCHO_PANTALLA_JUEGO(),
                Parametros.getInstance().getALTO_PANTALLA_JUEGO()
            );
        add(panelPresentacion,new Integer(0));
        panelPresentacion.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuItOpciones = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asgard");
        setMaximumSize(new java.awt.Dimension(640, 482));
        setMinimumSize(new java.awt.Dimension(640, 482));
        setPreferredSize(new java.awt.Dimension(640, 482));
        setResizable(false);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Editor de mapas...");
        jMenuItem1.addActionListener(e -> jMenuItem1ActionPerformed(e));
        jMenu1.add(jMenuItem1);

        menuItOpciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        menuItOpciones.setText("Opciones");
        menuItOpciones.addActionListener(e -> menuItOpcionesActionPerformed(e));
        jMenu1.add(menuItOpciones);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(e -> jMenuItem2ActionPerformed(e));
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        pack();
    }

    /**
     * Sale del programa.
     * @param evt 
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    /**
     * Abre el editor de pantallas
     * @param evt 
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        editor.Main editorMapas = new editor.Main();
        editorMapas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Cuando demos a la X de cerrar, SOLO destruirá este nuevo panel
        editorMapas.setVisible(true);
    }

    /**
     * Abre el diálogo de opciones
     * @param evt 
     */
    private void menuItOpcionesActionPerformed(java.awt.event.ActionEvent evt) {
        DialogoMenu dialogoMenu = new DialogoMenu(this,false);
        dialogoMenu.setLocationRelativeTo(panelJuego);
        
        dialogoMenu.setVisible(true);
        PanelJuego.getPanelDialogo().setVisible(false);
        this.panelJuego.getPersonaje().setFinDialogo(true);
        dialogoMenu.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException|InstantiationException|IllegalAccessException|UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private JMenu jMenu1;
    private JMenuBar jMenuBar1;
    private JMenuItem jMenuItem1;
    private JMenuItem jMenuItem2;
    private JMenuItem menuItOpciones;

    /**
     * Fija el atributo <code>PanelJuego</code>
     * @param panelJuego Atributo <code>PanelJuego</code>
     */
    public void setPanelJuego(PanelJuego panelJuego){
        this.panelJuego = panelJuego;
    }

    /**
     * Devuelve un elemento <code>PanelJuego</code>
     * @return Atributo <code>PanelJuego</code>
     */
    public PanelJuego getPanelJuego() {
        return panelJuego;
    }
}
